### ISSUE TITLE
 Cannot find module ... @tsndr/cloudflare-worker-jwt/utils

### ISSUE THREAD

**Issue by devinellis** [tsndr/cloudflare-worker-jwt#66]
FYI, builds on Cloudflare Pages started failing in the last few days:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/opt/buildhome/repo/node_modules/@tsndr/cloudflare-worker-jwt/utils' imported from /opt/buildhome/repo/node_modules/@tsndr/cloudflare-worker-jwt/index.js
```

My package.json was: `@tsndr/cloudflare-worker-jwt": "^2.2.1`. I removed the `^` and builds are working again. I also tried `2.4.3` but saw the same error when running locally.

In case it matters, I use the module format to import the library:
```
import jwt from '@tsndr/cloudflare-worker-jwt'
```

Deployment Log:
- Success 10:40AM January 20, 2024 (^2.2.1)
- Failed 5:42PM January 25, 2024 (^2.2.1)
- Success 1:46PM January 27, 2024 (2.2.1)

**Comment by vnphanquang** [comment]
This started in [2.4.1](https://github.com/tsndr/cloudflare-worker-jwt/compare/v2.4.0...v2.4.1) when `src/utils.ts` was introduced. The problem is that `tsc` outputs the import statement for `utils` module as:

```javascript
// index.js
import { ... } from "./utils";
```

This is incompatible with Node's ESM algorithm, which requires explicit `.js` extension. A possible fix is to include `.js` in `src/index.ts`

```typescript
// src/index.ts
import { ... } from "./utils.js"
```

`tsc` will keep `.js` in output. However, test cases will fail because jest throws a `Cannot find module './utils.js' from 'src/index.ts'` error.

Hopefully these info are helpful. I will keep experimenting when i have some more time.

---

For the record, I'm using `svelte-kit@2.5.0` and "@sveltejs/adapter-cloudflare@4.1.0".

**Comment by tsndr** [comment]
I'm looking into this, sorry for the inconvenience.

**Comment by tsndr** [comment]
Hey guys, I've created a test project, but for me everythings working:

https://github.com/tsndr/cloudflare-worker-jwt-test

**Comment by focus-at** [comment]
same, trying in nuxt: 3.4.3 project

**Comment by vnphanquang** [comment]
It is not the best fix and one I'm really satisfied with but inlining `utils.ts` inside `index.ts` would effectively be enough...

**Comment by Eusebiotrigo** [comment]
It is happening to us also when running tests in vitest.

**Comment by tsndr** [comment]
Hey guys, I've now added [`esbuild`](https://github.com/evanw/esbuild) and released the change with [`v2.4.6`](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.4.6), this should hopefully fix this issue.

@vnphanquang I appreciate you effort with the PR, but I've just switched over from js to ts a little while ago and really like to keep it that way. I think a bundler is the best way forward for now, but I'm also alway open for feedback and suggestions :)

**Comment by vnphanquang** [comment]
@tsndr thank you. No worries I understand 😀

**Comment by Eusebiotrigo** [comment]
Thank you very much!!!
