### ISSUE TITLE
Verification order

### ISSUE THREAD

**Issue by naourass** [tsndr/cloudflare-worker-jwt#87]
Shouldn't the _signature_ verification come before the _expiry_ verification, so if the token is expired, we can make sure that its signature is valid before refreshing it?

https://github.com/tsndr/cloudflare-worker-jwt/blob/d3d7e10b60cc886b426faa15fa4b0060a5b32915/src/index.ts#L213-L229

With the current order, I can't find a way to make sure that an expired token's signature is valid before proceeding to issuing a fresh one. Or am I missing something?

**Comment by tsndr** [comment]
My thought process was to only verify the signature if necessary, because that's what uses up CPU time. Why waste CPU time if we already know that the token is expired.

I wouldn't recommend issuing a new token in exchange for an expired one, but rather have a user sign in again to keep your system secure. You could also look at the [OAuth](https://datatracker.ietf.org/doc/html/rfc6749#section-1.4) approach which uses an **Access Token** in conjunction with a **Refresh Token**.

**Comment by naourass** [comment]
I mean although I have a refresh token mechanism, I believe that verifying the access token signature validity before verifying the refresh token is still necessary. Wondering what are your thoughts about this?

**Comment by devondragon** [comment]
FWIW I agree with @tsndr. Any refresh mechanism should be driven by a separate long lived refresh token. I can't think of any circumstance where you would want to verify the signature on an expired token...

**Comment by naourass** [comment]
After further research, I see that specs like OAuth and OIDC don't really mandate validating the signature of an expired access token before checking the refresh token. I've also found that auth service providers (like Keycloak and other OSS implementations...) proceed directly to the refresh token step without validating the expired access token. There could be some cases where you need some logging or audit trails that could be based on expired access token and of which the validation might be a good idea, but those are vey special cases. So I think that the current implementation is fine for now and that the issue could be closed!
